apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: co326
      defaultBucket: motor_health
    secureJsonData:
      token: ${INFLUX_TOKEN}